let time = 5;
// O'g'illarim go'sht yedi
const allData = [
    {
        wordId: 1,
        category: "ismlar",
        time: time,
        uz: "Ota",
        arabic: `أَبٌّ`,
        en: "",
        ru: "",   
    },
    {
        wordId: 2,
        category: "fe'llar",
        time: time,
        uz: "Qurmoq",
        arabic: `بَنَى`,
        en: "",
        ru: "",   
    },
    {
        wordId: 3,
        category: "gaplar",
        time: time,
        uz: "Xo'roz go'sht yedi",
        arabic: `أَكَلَ الدِّيكُ لَحْمٌ`,
        en: "",
        ru: "",   
    },
    {
        wordId: 4,
        category: "ismlar",
        time: time,
        uz: "Eshik",
        arabic: `بَابٌ`,
        en: "",
        ru: "",   
    },
    {
        wordId: 5,
        category: "gaplar",
        time: time,
        uz: "Otam go'sht yedi",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 6,
        category: "gaplar",
        time: time,
        uz: "Chavandoz go'sht yedi",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 7,
        category: "fe'llar",
        time: time,
        uz: "O'smoq",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 8,
        category: "ismlar",
        time: time,
        uz: "Men",
        arabic: `أَنَا`,
        en: "",
        ru: "",   
    },
    {
        wordId: 9,
        category: "fe'llar",
        time: time,
        uz: "Yemoq",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 10,
        category: "gaplar",
        time: time,
        uz: "Shifokor go'sht yedi",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 11,
        category: "ismlar",
        time: time,
        uz: "O'g'il",
        arabic: `إِبْنٌ`,
        en: "",
        ru: "",   
    },
    {
        wordId: 12,
        category: "ismlar",
        time: time,
        uz: "Sen",
        arabic: `أَنْتَ`,
        en: "",
        ru: "",   
    },
    {
        wordId: 13,
        category: "fe'llar",
        time: time,
        uz: "Yozmoq",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 14,
        category: "ismlar",
        time: time,
        uz: "Qizlar",
        arabic: `بَنَاتٌ`,
        en: "",
        ru: "",   
    },
    {
        wordId: 15,
        category: "fe'llar",
        time: time,
        uz: "Uxlamoq",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 16,
        category: "gaplar",
        time: time,
        uz: "Ukam go'sht yedi",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 17,
        category: "ismlar",
        time: time,
        uz: "Qiz",
        arabic: `بِنْتٌ`,
        en: "",
        ru: "",   
    },
    {
        wordId: 18,
        category: "gaplar",
        time: time,
        uz: "Ustozim go'sht yedi",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 19,
        category: "fe'llar",
        time: time,
        uz: "Yaxshi ko'rmoq",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 20,
        category: "gaplar",
        time: time,
        uz: "Ishchi go'sht yedi",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 21,
        category: "gaplar",
        time: time,
        uz: "Akam go'sht yedi",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 22,
        category: "fe'llar",
        time: time,
        uz: "Tavba qilmoq",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 23,
        category: "ismlar",
        time: time,
        uz: "Mebel",
        arabic: `أَثَاثٌ`,
        en: "",
        ru: "",   
    },
    {
        wordId: 24,
        category: "fe'llar",
        time: time,
        uz: "Bormoq, ketmoq",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 25,
        category: "gaplar",
        time: time,
        uz: "Singlim go'sht yedi",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 26,
        category: "gaplar",
        time: time,
        uz: "Hodim go'sht yedi",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 27,
        category: "ismlar",
        time: time,
        uz: "Isbot",
        arabic: `إِثْبَاتٌ`,
        en: "",
        ru: "",   
    },
    {
        wordId: 28,
        category: "fe'llar",
        time: time,
        uz: "Kirmoq",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 29,
        category: "fe'llar",
        time: time,
        uz: "Yig'moq",
        arabic: ``,
        en: "",
        ru: "",   
    },
    {
        wordId: 30,
        category: "ismlar",
        time: time,
        uz: "Kiyimlar",
        arabic: `ثِيَابٌ`,
        en: "",
        ru: "",   
    },

]

// console.log(allData);
